### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by jiewang2** [AgoraIO-Community/Agora-Rust-SDK#2]
In https://github.com/AgoraIO-Community/Agora-Rust-SDK/blob/026a93fdf36bafc5e1bf4476cd19022ee6f2b556/agorartc-sys/src/agorartc/mod.rs#L1263, `set_video_encoder_configuation` should be `set_video_encoder_configuration`.

**Comment by YiqingJackieHuang** [comment]
Thanks for reporting! We will fix it ASAP.
